version: '3'
services:
  databases:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=passowrd
    - MYSQL_USER=user
    - MYSQL_PASSWORD=password
    - MYSQL_DATABASE=demodb
  web:
    image: nginx
    ports: 
     - 8083:80
  cicd:
    image: jenkins/jenkins:latest
    container_name: jenkins_ci
    ports:
     - "8082:8080"
  nexus:
    image: sonatype/nexus
    ports:
     - "8081:8081"
